site_name: Python3 Editor Documentation
theme: readthedocs
docs_dir: 'doc'
pages:
    - 'Home': 'index.md'
    - 'Core':
        - 'Comments': 'core/comments.md'
        - 'Boolean': 'core/boolean.md'
        - 'Number': 'core/number.md'
        - 'Comparison': 'core/comparison.md'
        - 'None': 'core/none.md'
        - 'String': 'core/string.md'
        - 'Function': 'core/function.md'
        - 'List & Tuple': 'core/listtuple.md'
        - 'Set': 'core/set.md'
        - 'Dictionary': 'core/dictionary.md'
        - 'Standard Input & Output': 'core/inputoutput.md'