site_name: Python3 Editor Documentation
theme: readthedocs
docs_dir: 'doc'
nav:
    - 'Home': 'index.md'
    - 'Core':
        - 'Comments': 'core/comments.md'
        - 'Boolean': 'core/boolean.md'
        - 'Number': 'core/number.md'
        - 'Comparison': 'core/comparison.md'
        - 'None': 'core/none.md'
        - 'String': 'core/string.md'
        - 'Function': 'core/function.md'
        - 'List & Tuple': 'core/listtuple.md'
        - 'Set': 'core/set.md'
        - 'Dictionary': 'core/dictionary.md'
        - 'Standard Input & Output': 'core/inputoutput.md'
    - 'Standard Python Libraries':
        - 'Intro': 'modules/index.md'
        - 'math': 'modules/math.md'
        - 'random': 'modules/random.md'
        - 'string': 'modules/string.md'
        - 'time': 'modules/time.md'
        - 'urllib': 'modules/urllib.md'
        - 'turtle': 'modules/turtle.md'
        - 'tkinter': 'modules/tkinter.md'
    - 'Extra Python Libraries':
        - 'Intro': 'extralibs/index.md'
        - 'requests': 'extralibs/requests.md'
        - 'bottle': 'extralibs/bottle.md'
        - 'matplotlib': 'extralibs/matplotlib.md'
        - 'numpy': 'extralibs/numpy.md'
        - 'jinja2': 'extralibs/jinja2.md'
